### ISSUE TITLE
`Chart.lock` is outdated for `RELEASE_2`

### ISSUE THREAD

**Issue by jlarfors** [OPSWAT/metadefender-k8s#4]
Cannot use `RELEASE_2` from tools like ArgoCD because the `Chart.lock` has not been updated.

I saw in a recent commit the `Chart.lock` was deleted. Another fix would be to update it.

# RELEASE_2 with current Chart.lock

```console
> helm dependency build
Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies
```

# RELEASE_2 with updated Chart.lock

```console
> helm dependency update
...
...

> git diff
-digest: sha256:3e52943d17ce8ebe3433685e4a4ba8e63c5c0b7a82ac0d1f7a8bf45e3ced52d4
-generated: "2022-03-28T19:56:16.202347259+03:00"
+digest: sha256:ffaa808dd28e31818ee28fedd36b6ec1868cb039f6e3d9159a83acbc0ff02f78
+generated: "2022-05-31T11:26:08.017351+03:00"
```

Any chance you can make a new release, either from the current `main` branch (with deleted `Chart.lock`) or simply update it?

**Comment by acsoric** [comment]
RELEASE_3 should not contain Chart.lock anymore
